### ISSUE TITLE
ARIA controls don't work

### ISSUE THREAD

**Issue by mcladyz** [happyworm/jPlayer#283]
Controlling playback with keyboard no longer works (Arrow keys and space, at least). These keys were removed in commit 616569799c7cb52f49b218e7257605e3b95f77b5 but ARIA should enable them, right?

Version: 2.9.0
Browser: Iceweasel (Firefox) 31.3.0

**Comment by mcladyz** [comment]
Bump

**Comment by thepag** [comment]
The migration log and change log hold info on this change:
https://github.com/happyworm/jPlayer/blob/master/MIGRATION.md

The keys were changed, since space and arrow keys are supposed to be reserved for ARIA operations.

**Comment by thepag** [comment]
The documentation had also been updated... 
http://jplayer.org/latest/developer-guide/#jPlayer-option-keyBindings

**Comment by mcladyz** [comment]
Indeed. It seems I misunderstood how ARIA should work (These keys are reserved for std navigation).
