### ISSUE TITLE
IE8 not working on local disk

### ISSUE THREAD

**Issue by jusfeel** [happyworm/jPlayer#307]
Since I have spent so long on this ( IE8 with flash), I feel like writing something. Really small issue I guess but I really give up trying to find out why and how. I downloaded the new version and the flash on IE8 just won't work in my PC local files system if I open it. (maybe flash related??) Once I almost gave up and tried uploading to a test server to give a final try...magic! It worked. 

Your work is totally valuable!

**Comment by thepag** [comment]
That is a [Flash Security](http://jplayer.org/latest/developer-guide/#jPlayer-flash-security) restriction. Glad you got it figured out.
