### ISSUE TITLE
Click on previous button does not loop in playlist

### ISSUE THREAD

**Issue by kamalgo** [happyworm/jPlayer#312]
when the current index is 0， click event on the previous button does not make the current index to the last item of the playlist.
May be the code in line 456 of dist/addon/jplayer.playlist.js should be changed from
<code>if(this.loop && this.options.playlistOptions.loopOnPrevious || index < this.playlist.length - 1) {</code>
to
<code>if(this.loop && this.options.playlistOptions.loopOnPrevious || index < this.playlist.length) {</code>

**Comment by thepag** [comment]
The clue was in the code... The `loopOnPrevious` option. Your hack would only break it.

The docs:
http://jplayer.org/latest/demo-02-jPlayerPlaylist/

loopOnPrevious : Boolean : If loop is active, the playlist will loop back to the end when executing previous().
