### ISSUE TITLE
jplayer how to display “buffering” notification

### ISSUE THREAD

**Issue by ShankarPrakashG** [happyworm/jPlayer#340]
I have gone through the documentation and demos, but con't find correct event to notify user that track is not playing because of buffering(i.e when a user click on play and the track is not playing because it's buffering and also the track stopped in the middle because there in not enough buffered data due to slow connection or some other reason)

**Comment by thepag** [comment]
You use the waiting event, and the playing event. But only Safari and iOS follow the spec in a sensible manner (IMO), but the others raise the events when you change current time.
