### ISSUE TITLE
one of nine .mp3 will not play

### ISSUE THREAD

**Issue by be-sign** [happyworm/jPlayer#367]
hi everyone,

i use jplayer for the portfolio of a musician. alles players will work perfect. only in one section, there is a player with 9 mp3 in the playlist. and titel nr. 4 (i can hear your heartbeat) will not play - however, there is no idea why. all links are correct, mp3 and ogg are the same kind and quality, as the other 8 titles.
have i overlook something?

http://www.ralf-olbrich.de/pages/besetzungen/solo/solo_issue.html

thanks, bernd

**Comment by vlinder** [comment]
The link says 404.
http://www.ralf-olbrich.de/resources/besetzungen/solo/04/YourHeartBeat.ogg

Suspected you had a typo so I changed "Beat" to "beat" and then in worked. Unix servers are case sensitive mostly.

This one works.
http://www.ralf-olbrich.de/resources/besetzungen/solo/04/YourHeartbeat.ogg

**Comment by be-sign** [comment]
oh! this is embarassing. i had to know this. sorry for stressing you with this "problem"...

bernd
